import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstackQueryProvider from "@/providers/tanstack-react-query-provider";
import ReduxProvider from "@/providers/redux-toolkit-provider";
import { Suspense } from "react";
import StoreUserLoader from "@/components/store-user/StoreUserLoader";
import StoreUser from "@/components/store-user/StoreUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackQueryProvider>
          <ReduxProvider>
            <Suspense fallback={<StoreUserLoader />}>
              <StoreUser />
            </Suspense>
            {children}
          </ReduxProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
};
